CREATE TABLE `recipe_variants` (
	`id` text PRIMARY KEY NOT NULL,
	`recipe_id` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`ingredients` text,
	`instructions` text,
	`servings` integer,
	`yield` text,
	`cook_time` integer,
	`prep_time` integer,
	`total_time` integer,
	`rest_time` integer,
	`difficulty` text,
	`cuisine` text,
	`category` text,
	`diet` text,
	`image_url` text,
	`source_url` text,
	`source_author` text,
	`equipment` text,
	`notes` text,
	`nutrition` text,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`recipe_id`) REFERENCES `recipes`(`id`) ON UPDATE no action ON DELETE cascade
);
